image: debian:buster

stages:
  - build
  - build-iso

build:
  stage: build
  script:
  - apt update && apt install --no-install-recommends -y make wget ca-certificates
  - make download_extra
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

build-iso:
  stage: build-iso
  script:
  - apt update
  - apt install -y sudo make
  - make install_buildenv
  - sudo sed -i '1161s%umount%#umount%' /usr/share/debootstrap/functions
  - sudo mount -o remount,dev /builds
  - make
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  cache:
    paths:
      - cache/
  interruptible: true
