# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  configuration: doc/md/conf.py

# Optionally set the version of Python and requirements required to build your docs
# https://github.com/rtfd/readthedocs.org/issues/5250
python:
  version: 3.5

python:
  install:
    - requirements: doc/md/requirements.txt
